# Kitty Configuration File


# ============================================================================
# 字体配置
# ============================================================================
font_family      JetBrainsMono Nerd Font Mono Italic
bold_font        JetBrainsMono Nerd Font Mono Bold Italic
italic_font      JetBrainsMono Nerd Font Mono SemiBold Italic
bold_italic_font JetBrainsMono Nerd Font Mono Bold Italic
font_size 15

# 字体特性
disable_ligatures never

# ============================================================================
# smear cursor
# ============================================================================
cursor_trail 2
cursor_trail_decay 0.3 0.5

cursor_blink_interval 0

# ============================================================================
# 窗口配置
# ============================================================================

# 隐藏标题栏和边框
hide_window_decorations titlebar-only
# macOS 特定设置
macos_titlebar_color background
macos_show_window_title_in none

# 窗口边距
window_margin_width 0
window_padding_width 0
single_window_padding_width -1

# ============================================================================
# 标签页配置
# ============================================================================
# 隐藏标签栏
tab_bar_style hidden

# ============================================================================
# 背景图片配置
# ============================================================================
background_image /Users/liuzihao/Documents/wallPaper/Noelle/forItermIn95Percent.jpg
background_image_layout scaled

# ============================================================================
# 主题配置
# ============================================================================
include onedark.conf

# 背景蒙版 - 可调整透明度（0.0-1.0，值越大越暗）
background_tint 0.95
# background_tint_color 0.992 0.965 0.890
background_opacity 0.95
background #000000

# 颜色增强设置
# 禁用最小对比度调整，使用原始颜色
minimum_contrast 0

# macOS 颜色空间设置，使用 displayp3 以获得更鲜艳的颜色
# !!!!! 很关键，获得鲜艳的色彩
# !!!!! 只有用display3,实际测得值才和iTerm2完全一样！！
macos_colorspace displayp3

# 禁用文本对比度增强
# text_contrast_adjustment 0

# Bell
enable_audio_bell no
visual_bell_duration 0.0

# URL
url_style curly
detect_urls yes
url_prefixes file ftp ftps gemini git gopher http https irc ircs kitty mailto news sftp ssh

# 鼠标
mouse_hide_wait 3.0
copy_on_select yes

# Shell
# 启动时先打开tmux
shell /bin/zsh -l -c "tmux attach || tmux"
shell_integration enabled

confirm_os_window_close 0

# ============================================================================
# 快捷键配置
# ============================================================================
# 清除所有默认快捷键
clear_all_shortcuts no

map cmd+c copy_to_clipboard
map cmd+v paste_from_clipboard

# Tmux 快捷键(cmd+符号 -> ctrl+space+符号)
map cmd+1 send_text all \x001
map cmd+2 send_text all \x002
map cmd+3 send_text all \x003
map cmd+4 send_text all \x004
map cmd+5 send_text all \x005
map cmd+6 send_text all \x006
map cmd+7 send_text all \x007
map cmd+8 send_text all \x008
map cmd+9 send_text all \x009
map cmd+0 send_text all \x000
map cmd+w send_text all \x00c
map cmd+t send_text all \x00n
map cmd+n send_text all \x00n
map cmd+- send_text all \x00-
map cmd+= send_text all \x00=
map cmd+r send_text all \x00r


# ============================================================================
# macOS 特定配置
# ============================================================================
macos_option_as_alt yes
macos_quit_when_last_window_closed yes
